name: CI Process for Imperium Furniture

on:
  push:
    branches:
      - feature/*
      - bug/*
      - hotfix/*
  pull_request:
    branches:
      - feature/*
      - develop
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up repo
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install
    - name: Build code
      run: npm run build && npm run generate
    - name: Lint check
      run: npm run lint
